// <auto-generated />
using System;
using AdCreative.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdCreative.DataAccess.Migrations
{
    [DbContext(typeof(WordContext))]
    [Migration("20240926131823_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdCreative.Domain.WordAdd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountWord")
                        .HasColumnType("int");

                    b.Property<string>("UniqueId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Word")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("WordAdd", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountWord = 7,
                            UniqueId = "47b63467-7d4d-48e7-b81b-8fcd4d8b183e",
                            Word = "AbCdEfG"
                        },
                        new
                        {
                            Id = 2,
                            CountWord = 12,
                            UniqueId = "6be64795-9d99-4765-ac7a-6ed15aba97c0",
                            Word = "Test2AbCdEfG"
                        },
                        new
                        {
                            Id = 3,
                            CountWord = 13,
                            UniqueId = "c2f8bbce-2eee-4f3a-887b-97b2ea11dd7c",
                            Word = "TeStUcAbCdEfG"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
