// <auto-generated />
using System;
using AdCreative.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdCreative.DataAccess.Migrations
{
    [DbContext(typeof(WordContext))]
    partial class WordContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdCreative.Domain.WordAdd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountWord")
                        .HasColumnType("int");

                    b.Property<string>("Word")
                        .HasMaxLength(50)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("WordAdd", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountWord = 7,
                            Word = "AbCdEfG"
                        },
                        new
                        {
                            Id = 2,
                            CountWord = 12,
                            Word = "Test2AbCdEfG"
                        },
                        new
                        {
                            Id = 3,
                            CountWord = 13,
                            Word = "TeStUcAbCdEfG"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
